import argparse

import matplotlib.pyplot as plt
import numpy as np


def QPSK(data: np.ndarray):
    """Perform QPSK modulation of data bitstream"""
    x_radians = data * 2 * np.pi / 4 + np.pi / 4
    x_symbols = np.cos(x_radians) + 1j * np.sin(x_radians)

    return x_symbols


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--num-symbols", type=int, default=1000)
    parser.add_argument("--noise-power", type=float, default=0.00)
    parser.add_argument(
        "--phase-noise-strength",
        type=float,
        default=0.00,
        help="Phase noise generated by local oscillator jitter",
    )
    args = parser.parse_args()

    # Generate data stream
    data_stream = np.random.randint(0, 4, args.num_symbols)

    # Add noise and phase noise
    noise = (
        np.random.randn(args.num_symbols) + 1j * np.random.randn(args.num_symbols)
    ) / np.sqrt(2)
    phase_noise = np.random.randn(len(data_stream)) * args.phase_noise_strength

    data_symbols = (QPSK(data_stream) + noise * np.sqrt(args.noise_power)) * np.exp(
        1j * phase_noise
    )

    # Plot
    plt.plot(np.real(data_symbols), np.imag(data_symbols), ".")
    plt.suptitle("QPSK modulation")
    plt.title(
        f"Noise power = {args.noise_power}, Phase noise strength: {args.phase_noise_strength}"
    )
    plt.grid(True)
    plt.xlabel("I")
    plt.ylabel("Q")
    plt.axis("equal")
    plt.show()
